version: 2.1
jobs:
  build:
    docker:
      - image: circleci/node
    steps:
      - checkout # check out the code in the project directory
      - run: echo "hello world" # run the `echo` command
      - run: echo "hello world 2" # run the `echo` command